### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/home#11]
Should be resolved before going live
<img width="534" alt="Skjermbilde 2024-07-29 kl  15 13 37" src="https://github.com/user-attachments/assets/b40d8da4-c578-420b-9b88-735d2bb75423">

**Comment by blt950** [comment]
aha, @bjerrecs  I thought it worked. What's missing exactly? As all info is already present on the website? 

What does the CORS block today?

**Comment by bjerrecs** [comment]
@blt950 nothing you should do, i need to read the errors one more time, 1/3 of the errors are resolved.

**Comment by bjerrecs** [comment]
fixed by CORS change on the VPS
