### ISSUE TITLE
Announcement component

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/home#8]
What's left:

- [x] Date should be "14 JUN" like in AIRACS, short and sweet
- [ ] See if possible to add a "Appointment" tag if the thread has been posted under this tag on forum as well?

**Comment by bjerrecs** [comment]
Currently, we pull all posts with that tag `?filter[tag]=announcements`

**Comment by bjerrecs** [comment]
And date format has been changed
![image](https://github.com/user-attachments/assets/007158d3-eb0b-4270-b559-1f089432c191)
